generators:
- app-admission-controller.yaml
- app-exporter.yaml
- app-operator.yaml
- athena.yaml
- cluster-api-cleaner-cloud-director.yaml
- cluster-api-monitoring.yaml
- cluster-api-provider-cloud-director.yaml
- cluster-api.yaml
- cluster-apps-operator.yaml
- dashboards.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-route53.yaml
- encryption-provider-operator.yaml
- etcd-backup-operator.yaml
- exception-recommender.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- grafana.yaml
- happa.yaml
- kyverno-policies-connectivity.yaml
- kyverno-policies-dx.yaml
- kyverno-policies-observability.yaml
- kyverno-policies-ux.yaml
- kyverno-policies.yaml
- kyverno-policy-operator.yaml
- kyverno.yaml
- loki.yaml
- macropower-analytics-panel-server.yaml
- nginx-ingress-controller-app.yaml
- oauth2-proxy.yaml
- organization-operator.yaml
- prometheus-meta-operator.yaml
- prometheus-remotewrite.yaml
- prometheus-rules.yaml
- promxy-app.yaml
- pss-operator.yaml
- rbac-operator.yaml
- silence-operator.yaml
- sloth-rules.yaml
- sloth.yaml
- starboard-exporter.yaml
- teleport-operator.yaml
- trivy-operator.yaml
- trivy.yaml
