api_version: generators.giantswarm.io/v1
app_catalog: control-plane-catalog
app_destination_namespace: monitoring
app_name: prometheus-operator-app
app_version: 1.3.0
kind: Konfigure
metadata:
  annotations:
    config.kubernetes.io/function: |-
      exec:
        path: /plugins/konfigure
  name: prometheus-operator-app
name: prometheus-operator-app
